# Generated by Django 4.0.4 on 2022-07-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kishan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=122)),
                ('last_name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('number', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
