# Generated by Django 4.0.4 on 2022-07-20 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kishan', '0002_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='first_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='last_name',
            new_name='lname',
        ),
    ]
